/**
 * Generated by BinFS
 */

package binfs_test

import (
	"time"

	"go.guoyk.net/binfs"
)

var (
	binfs3857b672471862eab426eba0622e44bd2cedbd5d = binfs.Chunk{
		Path: []string{"testdata1", "hello.txt"},
		Date: time.Unix(1562319241, 0),
		Data: []byte{
			0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x31, 0x0a,
		},
	}
	binfsc9ee995ffd32513f2b65f4fab85616d6aba6f26c = binfs.Chunk{
		Path: []string{"testdata2", "hello2.txt"},
		Date: time.Unix(1562319263, 0),
		Data: []byte{
			0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x0a,
		},
	}
	binfs7a01435522e27d84a14ce54639482d066bb7e928 = binfs.Chunk{
		Path: []string{"testdata2", "testdata3", "hello3.txt"},
		Date: time.Unix(1562319257, 0),
		Data: []byte{
			0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x0a,
		},
	}
)

func init() {
	binfs.Load(&binfs3857b672471862eab426eba0622e44bd2cedbd5d)
	binfs.Load(&binfsc9ee995ffd32513f2b65f4fab85616d6aba6f26c)
	binfs.Load(&binfs7a01435522e27d84a14ce54639482d066bb7e928)
}
